{"uuid": "22251a1d-def5-4c7d-83dd-95198393a213", "children": ["3ebb58b1-a954-4885-9b4e-bf230e64d93e"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1112be5d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/mobile_project/Android_CTY/conftest.py\", line 20, in driver\n    app = webdriver.Remote(appium_server_url, options=capabilities_options)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/appium/webdriver/webdriver.py\", line 253, in __init__\n    super().__init__(\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/appium/webdriver/webdriver.py\", line 344, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 427, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/urllib3/poolmanager.py\", line 459, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/Users/evgenijpuckov/PycharmProjects/QA_Auto_Appium/.venv/lib/python3.12/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1753610702893, "stop": 1753610702961}], "start": 1753610702893, "stop": 1753610703399}